### ISSUE TITLE
Issues adding plugin to runelite with IntelliJ

### ISSUE THREAD

**Issue by gumpy366** [CodePanter/another-bronzeman-mode#7]
Apologies if this has been asked before, but where should all of the files be going when installing with IntelliJ? I noticed you have wrappers, so I'm not sure if I'm putting this files in the correct folder. I tried moving files to the appropriate plugin locations, but they wouldn't manifest in my plugins list like the original bronzeman mode. If I am supposed to be using something besides IntelliJ for runelite, please let me know.

**Comment by CodePanter** [comment]
Hello! Did you close this because you figured it out? Because when it comes to playing, I just let it install itself through the runelite plugin hub, and when it comes to development you don''t want to move the files to the runelite repository, but use the testing code that is documented on the runelite wiki somewhere.
